### ISSUE TITLE
access to collection's item permalink?

### ISSUE THREAD

**Issue by constantx** [segmentio/metalsmith-collections#28]
Not sure how to get this… any tip?

**Comment by constantx** [comment]
found it :) apparently available with ` {{ path }} `

I found the plugins build order becomes increasingly important to get right, which is not mentioned anywhere on any of the plugins so far, which makes using them together is not quite straight forward.

**Comment by yuvilio** [comment]
@constantx , agreed about the order.  I'd found, in my setup for example, that `metalsmith-tags` needed to come after `metalsmith-permalinks` to not clobber the `{{post.path}}`  property.
