### ISSUE TITLE
Contents of collection is html encoded

### ISSUE THREAD

**Issue by flatiron32** [segmentio/metalsmith-collections#43]
I have pulled in a collection of html files using this plugin. The collection is named posts. I then have a template that uses the collection
````
{{#each posts}}
  {{contents}}
{{/each}}
`````
This does print out the contents but the html is html encoded. '<' is '&lt;' for instance. What am I doing wrong?

My metalsmith.json is simple
````
{
  "metadata": {
    "site": {
      "title": "Tomaw Tech"    
    }
  },
  "plugins": {
    "metalsmith-collections": {
      "posts": "posts/*"
    },
    "metalsmith-page-titles":{},
    "metalsmith-in-place": {
      "engine": "handlebars"
    },
    "metalsmith-layouts": {
      "engine": "handlebars",
      "default": "layout.html"
    },
    "metalsmith-broken-link-checker": true
  }
}
````

**Comment by Taurean** [comment]
+1 having the same issue.

**Comment by s992** [comment]
You want to use three braces for unescaping HTML: `{{{contents}}}`.

**Comment by flatiron32** [comment]
Confirmed. I finally figured out it was my handlebars ignorance that was the main issue, but I failed to close this issue.
