### ISSUE TITLE
Collection from JSON?

### ISSUE THREAD

**Issue by poshaughnessy** [segmentio/metalsmith-collections#61]
I have a list page that I would like to template from a block of JSON, rather than from a set of markdown files. (I could create a file for each list item, but that seems excessive because they are just a few properties each, with no body, and I only need a list page, not pages for each of them individually).

The config could be something like this:

```
 Metalsmith(__dirname)
    .use(collections({
      talks: {
        json: 'content/talks.json'
      },
```

Might you be interested in adding this feature to metalsmith-collections? I'd be happy to try adding it in a fork and submitting a PR if so.

**Comment by poshaughnessy** [comment]
Took a quick look and it seems like this would be more of a change to Metalsmith itself? If it's OK, I'll just leave this issue open for a bit in case anyone has any suggestions though, thanks.

**Comment by renatorib** [comment]
+1 
I need this feature too. :D

**Comment by fidian** [comment]
I'm the author of [metalsmith-data-loader](https://github.com/tests-always-included/metalsmith-data-loader) and it should be able to load JSON for you. Assuming the default configuration and if you have something that can parse mustache templates ...

    ---
    data: content/talks.json
    ---
    <ul>
        {{#data}}
        <li><a href="{{href}}">{{title}}</a></li>
        {{/data}}
    </ul>

The above would work with a JSON file like this:

    [
        {
            "href": "/page1.html",
            "title": "This is page 1"
        }
    ]

Would this solve your data loading needs?

**Comment by poshaughnessy** [comment]
Thanks @fidian, yes that's what I was looking for! 

I actually realised afterwards I was over-complicating it and I should just write a markdown list page directly. But your plugin seems like the solution if I wanted to do that again - I just tried it out and I think I got it working fine. In case it helps others, I set it up like this:

`// build.js`

```
Metalsmith(__dirname)
    .use(dataLoader())
    // ... Various other config here ...
    .use(templates('handlebars'))    // NB. I'm using metalsmith-templates but I see it's now deprecated
    // ... Various other config here ...
```

`// src/talks.md`

```
---
title: Talks
data: content/talks.json
template: talks.hbs
---
# Talks
```

`// src/content/talks.json`

```
[
  {
    "href": "http://foo.com",
    "title": "Lorem Ipsum Talk"
  },
  {
    "href": "http://bar.com",
    "title": "Another Great Talk."
  }
]
```

`// templates/talks.hbs`

```
<ul>
  {{#data}}
  <li><a href="{{href}}">{{title}}</a></li>
  {{/data}}
</ul>
```

This produces:

`// build/talks/index.html`

```
<ul>
  <li><a href="http://foo.com">Lorem Ipsum Talk</a></li>
  <li><a href="http://bar.com">Another Great Talk.</a></li>
</ul>
```

Thanks again. I'm going to close this issue now.
