### ISSUE TITLE
Open to other maintainers?

### ISSUE THREAD

**Issue by benpolinsky** [segmentio/metalsmith-collections#80]
Hello.
Any chance someone could be brought aboard to help maintain this plugin? 
It's used by nearly everyone who uses Metalsmith.

Or at least some clarity that this is the final version and we should fork if we want to add features or help out with potential issues.

Thanks - love Metalsmith and hope it doesn't go away.

**Comment by MegaJ** [comment]
+1 I also want to see some of those PRs get merged. There are so many metalsmith repos that have little author activity this past year, despite issues issues/incoming PRs.

**Comment by RetrocadeNet** [comment]
+1 Would also like that. In the meantime I guess I am forced to just make a fork and use that fork until things move

**Comment by woodyrew** [comment]
We have got some maintainers added to this and other core Metalsmith plugins that have been neglected.
Many of the PRs have been merged now.
