### ISSUE TITLE
How to generate URLs using path variable?

### ISSUE THREAD

**Issue by gremo** [segmentio/metalsmith-collections#90]
My configuration (products collection):

```js
Metalsmith(__dirname)
  .source('./contents')
  .destination('./build')
  .clean(true)
  .use(collections({
    products: 'products/*.njk'
  }))
  .use(inPlace())
  .use(layouts({
    directory: '_layouts',
    default: 'base.njk'
  }))
  .build(function(err) {
    if (err) throw err;
  });
```

In my template `product.njk` (Nunjucks):

```nunjucks
---
title: Products
---

<h1>{{ title }}</h1>
<ul>
    {% for product in products %}
        <li>
            <a href="/{{ product.path }}">
                {{ product.title }}
            </a>
        </li>
    {% endfor %}
</ul>
```

Actually, `product.path` contains `/products\product-1.njk` which is not what I want.

Is possibile to generate URLs for collection elements? How?

**Comment by ismay** [comment]
Hi @gremo, the issue tracker is only for tracking work that needs to be done on our software (so bugs, features, etc.). For support questions we have a slack channel (http://metalsmith-slack.herokuapp.com). That's where the devs hang out and where you'll get a quick answer to questions like these.

**Comment by gremo** [comment]
Thank you.
